name: limit
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - numba
  - scipy
  - pip

  # core install of LIMIT (editable recommended for dev)
  - pip:
      - -e .

      # CMF for validation runs
      - cmf>=2.0
